# Generated by Django 6.0.1 on 2026-01-28 11:05

import cloudinary.models
import curriculum.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionperfil', models.CharField(blank=True, max_length=50, null=True)),
                ('perfilactivo', models.IntegerField(default=1)),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('foto_perfil', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('nacionalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('lugarnacimiento', models.CharField(blank=True, max_length=60, null=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True, validators=[curriculum.models.validar_fecha_no_futura, curriculum.models.validar_rango_edad_realista])),
                ('numerocedula', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'La cédula debe contener exactamente 10 dígitos numéricos')])),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('estadocivil', models.CharField(blank=True, max_length=50, null=True)),
                ('licenciaconducir', models.CharField(blank=True, max_length=6, null=True)),
                ('telefonoconvencional', models.CharField(blank=True, max_length=15, null=True)),
                ('telefonofijo', models.CharField(blank=True, max_length=15, null=True)),
                ('direcciontrabajo', models.CharField(blank=True, max_length=50, null=True)),
                ('direcciondomiciliaria', models.CharField(blank=True, max_length=50, null=True)),
                ('sitioweb', models.CharField(blank=True, max_length=60, null=True)),
                ('mostrar_experiencia', models.BooleanField(default=True)),
                ('mostrar_reconocimientos', models.BooleanField(default=True)),
                ('mostrar_cursos', models.BooleanField(default=True)),
                ('mostrar_productos_academicos', models.BooleanField(default=True)),
                ('mostrar_productos_laborales', models.BooleanField(default=True)),
                ('mostrar_venta_garage', models.BooleanField(default=False)),
                ('imprimir_experiencia', models.BooleanField(default=True, verbose_name='¿Imprimir Experiencia?')),
                ('imprimir_reconocimientos', models.BooleanField(default=True, verbose_name='¿Imprimir Reconocimientos?')),
                ('imprimir_cursos', models.BooleanField(default=True, verbose_name='¿Imprimir Cursos?')),
                ('imprimir_productos_academicos', models.BooleanField(default=True, verbose_name='¿Imprimir Productos Académicos?')),
                ('imprimir_productos_laborales', models.BooleanField(default=True, verbose_name='¿Imprimir Productos Laborales?')),
                ('imprimir_venta_garage', models.BooleanField(default=True, verbose_name='¿Imprimir Venta Garage?')),
            ],
            options={
                'verbose_name': 'Datos Personales',
                'verbose_name_plural': 'Datos Personales',
                'db_table': 'datospersonales',
            },
        ),
        migrations.CreateModel(
            name='CursosRealizados',
            fields=[
                ('idcursorealizado', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(max_length=100)),
                ('fechainicio', models.DateField(validators=[curriculum.models.validar_fecha_no_futura])),
                ('fechafin', models.DateField(blank=True, null=True, validators=[curriculum.models.validar_fecha_no_futura])),
                ('totalhoras', models.IntegerField(blank=True, null=True)),
                ('descripcioncurso', models.TextField(blank=True, null=True)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('emailempresapatrocinadora', models.EmailField(blank=True, max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='curriculum.datospersonales')),
            ],
            options={
                'db_table': 'cursosrealizados',
                'ordering': ['-fechainicio'],
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('idexperiencialaboral', models.AutoField(primary_key=True, serialize=False)),
                ('cargodesempenado', models.CharField(max_length=100)),
                ('nombrempresa', models.CharField(max_length=50)),
                ('lugarempresa', models.CharField(blank=True, max_length=50, null=True)),
                ('emailempresa', models.EmailField(blank=True, max_length=100, null=True)),
                ('sitiowebempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoempresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoempresarial', models.CharField(blank=True, max_length=60, null=True)),
                ('fechainiciogestion', models.DateField(validators=[curriculum.models.validar_fecha_no_futura])),
                ('fechafingestion', models.DateField(blank=True, null=True, validators=[curriculum.models.validar_fecha_no_futura])),
                ('descripcionfunciones', models.TextField(blank=True, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='curriculum.datospersonales')),
            ],
            options={
                'db_table': 'experiencialaboral',
                'ordering': ['-fechainiciogestion'],
            },
        ),
        migrations.CreateModel(
            name='ProductosAcademicos',
            fields=[
                ('idproductoacademico', models.AutoField(primary_key=True, serialize=False)),
                ('nombrerecurso', models.CharField(max_length=100)),
                ('clasificador', models.CharField(choices=[('Ingeniería', 'Ingeniería'), ('Tecnología', 'Tecnología'), ('Docencia', 'Docencia'), ('Investigación', 'Investigación'), ('Otro', 'Otro')], max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(default=datetime.date.today, validators=[curriculum.models.validar_fecha_no_futura])),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='curriculum.datospersonales')),
            ],
            options={
                'db_table': 'productosacademicos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ProductosLaborales',
            fields=[
                ('idproductoslaborales', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('fechaproducto', models.DateField(validators=[curriculum.models.validar_fecha_no_futura])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='curriculum.datospersonales')),
            ],
            options={
                'db_table': 'productoslaborales',
                'ordering': ['-fechaproducto'],
            },
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('idreconocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100)),
                ('fechareconocimiento', models.DateField(validators=[curriculum.models.validar_fecha_no_futura])),
                ('descripcionreconocimiento', models.TextField(blank=True, null=True)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='curriculum.datospersonales')),
            ],
            options={
                'db_table': 'reconocimientos',
                'ordering': ['-fechareconocimiento'],
            },
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('idventagarage', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_producto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_garage', to='curriculum.datospersonales')),
            ],
            options={
                'db_table': 'ventagarage',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
