# Generated by Django 6.0.1 on 2026-01-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/cursos/'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/experiencia/'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='productos_academicos/'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='productos_laborales/'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/reconocimientos/'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='ventas_garage/'),
        ),
    ]
