"""
Django settings for hojavida_project project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
import os
import cloudinary
import cloudinary.uploader
import cloudinary.api

# ============================
# BASE DIR
# ============================
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================
# SECURITY
# ============================
SECRET_KEY = 'django-insecure-uoilrv5vx0b3(rpn3j%3e1u=rzbvi@b&7h_g+xk^l&yyx+*!x_'

DEBUG = True

ALLOWED_HOSTS = ['*', '127.0.0.1', 'localhost', '0.0.0.0']


# ============================
# APPLICATIONS
# ============================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Cloudinary - IMPORTANTE: cloudinary_storage ANTES de cloudinary
    # 'cloudinary_storage',
    # 'cloudinary',
    
    # Tu app
    'curriculum',
]


# ============================
# MIDDLEWARE
# ============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================
# URLS & WSGI
# ============================
ROOT_URLCONF = 'hojavida_project.urls'

WSGI_APPLICATION = 'hojavida_project.wsgi.application'


# ============================
# TEMPLATES
# ============================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # templates globales
        'APP_DIRS': True,                  # templates por app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ============================
# DATABASE
# ============================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ============================
# PASSWORD VALIDATION
# ============================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ============================
# INTERNATIONALIZATION
# ============================
LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True
USE_TZ = True


# ============================
# STATIC & MEDIA FILES
# ============================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Permitir tipos de archivo para ImageField
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB


# ============================
# CLOUDINARY CONFIGURATION
# ============================
# ⚠️ IMPORTANTE: Reemplaza 'TU_API_KEY' y 'TU_API_SECRET' con tus credenciales reales
# Obtén tus credenciales en: https://cloudinary.com/console

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dw1lgj3pa',
    'API_KEY': 'TU_API_KEY',           # ⚠️ CAMBIAR: Ve a https://cloudinary.com/console y copia tu API_KEY
    'API_SECRET': 'TU_API_SECRET',     # ⚠️ CAMBIAR: Ve a https://cloudinary.com/console y copia tu API_SECRET
}

cloudinary.config(
    cloud_name = CLOUDINARY_STORAGE['CLOUD_NAME'],
    api_key = CLOUDINARY_STORAGE['API_KEY'],
    api_secret = CLOUDINARY_STORAGE['API_SECRET'],
    secure = True
)

# Usar almacenamiento local por defecto
# Para producción, descomenta la línea siguiente después de configurar Cloudinary
# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Almacenamiento local para desarrollo
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'


# ============================
# DEFAULT PRIMARY KEY
# ============================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'